// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: landing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLandingByUserID = `-- name: GetLandingByUserID :one
SELECT id, user_id, headline, description, image_url, image_key, whatsapp_url, facebook_url, instagram_url, youtube_url, email, website_url, created_at, updated_at FROM landing_pages WHERE user_id = $1
`

func (q *Queries) GetLandingByUserID(ctx context.Context, userID int64) (LandingPage, error) {
	row := q.db.QueryRow(ctx, getLandingByUserID, userID)
	var i LandingPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Headline,
		&i.Description,
		&i.ImageUrl,
		&i.ImageKey,
		&i.WhatsappUrl,
		&i.FacebookUrl,
		&i.InstagramUrl,
		&i.YoutubeUrl,
		&i.Email,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLandingByUserID = `-- name: UpsertLandingByUserID :one
INSERT INTO landing_pages (
  user_id,
  headline,
  description,
  image_url,
  image_key,
  whatsapp_url,
  facebook_url,
  instagram_url,
  youtube_url,
  email,
  website_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (user_id) DO UPDATE
SET headline = EXCLUDED.headline,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    image_key = EXCLUDED.image_key,
    whatsapp_url = EXCLUDED.whatsapp_url,
    facebook_url = EXCLUDED.facebook_url,
    instagram_url = EXCLUDED.instagram_url,
    youtube_url = EXCLUDED.youtube_url,
    email = EXCLUDED.email,
    website_url = EXCLUDED.website_url,
    updated_at = NOW()
RETURNING id, user_id, headline, description, image_url, image_key, whatsapp_url, facebook_url, instagram_url, youtube_url, email, website_url, created_at, updated_at
`

type UpsertLandingByUserIDParams struct {
	UserID       int64       `json:"user_id"`
	Headline     pgtype.Text `json:"headline"`
	Description  pgtype.Text `json:"description"`
	ImageUrl     pgtype.Text `json:"image_url"`
	ImageKey     pgtype.Text `json:"image_key"`
	WhatsappUrl  pgtype.Text `json:"whatsapp_url"`
	FacebookUrl  pgtype.Text `json:"facebook_url"`
	InstagramUrl pgtype.Text `json:"instagram_url"`
	YoutubeUrl   pgtype.Text `json:"youtube_url"`
	Email        pgtype.Text `json:"email"`
	WebsiteUrl   pgtype.Text `json:"website_url"`
}

func (q *Queries) UpsertLandingByUserID(ctx context.Context, arg UpsertLandingByUserIDParams) (LandingPage, error) {
	row := q.db.QueryRow(ctx, upsertLandingByUserID,
		arg.UserID,
		arg.Headline,
		arg.Description,
		arg.ImageUrl,
		arg.ImageKey,
		arg.WhatsappUrl,
		arg.FacebookUrl,
		arg.InstagramUrl,
		arg.YoutubeUrl,
		arg.Email,
		arg.WebsiteUrl,
	)
	var i LandingPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Headline,
		&i.Description,
		&i.ImageUrl,
		&i.ImageKey,
		&i.WhatsappUrl,
		&i.FacebookUrl,
		&i.InstagramUrl,
		&i.YoutubeUrl,
		&i.Email,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
