// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Phone     string             `json:"phone"`
	Name      pgtype.Text        `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LandingPage struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Headline     pgtype.Text        `json:"headline"`
	Description  pgtype.Text        `json:"description"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	ImageKey     pgtype.Text        `json:"image_key"`
	WhatsappUrl  pgtype.Text        `json:"whatsapp_url"`
	FacebookUrl  pgtype.Text        `json:"facebook_url"`
	InstagramUrl pgtype.Text        `json:"instagram_url"`
	YoutubeUrl   pgtype.Text        `json:"youtube_url"`
	Email        pgtype.Text        `json:"email"`
	WebsiteUrl   pgtype.Text        `json:"website_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Rule struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Config    []byte             `json:"config"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Template struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	Body      string             `json:"body"`
	Type      string             `json:"type"`
	Channel   string             `json:"channel"`
	Language  pgtype.Text        `json:"language"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	ImageKey  pgtype.Text        `json:"image_key"`
}

type Token struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	IsRevoked  bool               `json:"is_revoked"`
	TokenType  string             `json:"token_type"`
	ClientIp   pgtype.Text        `json:"client_ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID            int64              `json:"id"`
	Phone         string             `json:"phone"`
	PasswordHash  string             `json:"password_hash"`
	PhoneVerified bool               `json:"phone_verified"`
	Name          pgtype.Text        `json:"name"`
	BusinessName  pgtype.Text        `json:"business_name"`
	City          pgtype.Text        `json:"city"`
	Address       pgtype.Text        `json:"address"`
	LocationUrl   pgtype.Text        `json:"location_url"`
	Plan          string             `json:"plan"`
	PlanStartedAt pgtype.Timestamptz `json:"plan_started_at"`
	PlanExpiresAt pgtype.Timestamptz `json:"plan_expires_at"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
