// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error
	DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error
	GetContactsByUserID(ctx context.Context, userID int64) ([]Contact, error)
	GetLandingByUserID(ctx context.Context, userID int64) (LandingPage, error)
	GetRuleByUserID(ctx context.Context, userID int64) (Rule, error)
	GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error)
	GetTemplateByUserID(ctx context.Context, userID int64) ([]Template, error)
	GetTokenByToken(ctx context.Context, token string) (Token, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	ListAllUsers(ctx context.Context) ([]User, error)
	RevokeAllUserTokens(ctx context.Context, userID int64) error
	RevokeAllUserTokensByType(ctx context.Context, arg RevokeAllUserTokensByTypeParams) error
	RevokeToken(ctx context.Context, token string) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error)
	UpdateTokenLastUsed(ctx context.Context, id int64) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpsertContact(ctx context.Context, arg UpsertContactParams) (Contact, error)
	UpsertContactBatch(ctx context.Context, arg UpsertContactBatchParams) error
	UpsertLandingByUserID(ctx context.Context, arg UpsertLandingByUserIDParams) (LandingPage, error)
	UpsertRule(ctx context.Context, arg UpsertRuleParams) (Rule, error)
}

var _ Querier = (*Queries)(nil)
