// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (user_id, name, body, type, channel, image_url, image_key, language, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, name, body, type, channel, language, is_default, created_at, updated_at, image_url, image_key
`

type CreateTemplateParams struct {
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Body      string      `json:"body"`
	Type      string      `json:"type"`
	Channel   string      `json:"channel"`
	ImageUrl  pgtype.Text `json:"image_url"`
	ImageKey  pgtype.Text `json:"image_key"`
	Language  pgtype.Text `json:"language"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.UserID,
		arg.Name,
		arg.Body,
		arg.Type,
		arg.Channel,
		arg.ImageUrl,
		arg.ImageKey,
		arg.Language,
		arg.IsDefault,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.Type,
		&i.Channel,
		&i.Language,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImageKey,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1 AND user_id = $2
`

type DeleteTemplateParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.UserID)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, user_id, name, body, type, channel, language, is_default, created_at, updated_at, image_url, image_key FROM templates WHERE id = $1 AND user_id = $2
`

type GetTemplateByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID, arg.UserID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.Type,
		&i.Channel,
		&i.Language,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImageKey,
	)
	return i, err
}

const getTemplateByUserID = `-- name: GetTemplateByUserID :many
SELECT id, user_id, name, body, type, channel, language, is_default, created_at, updated_at, image_url, image_key FROM templates WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetTemplateByUserID(ctx context.Context, userID int64) ([]Template, error) {
	rows, err := q.db.Query(ctx, getTemplateByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Body,
			&i.Type,
			&i.Channel,
			&i.Language,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name = $3,
    body = $4,
    type = $5,
    channel = $6,
    image_url = $7,
    image_key = $8,
    language = $9,
    is_default = $10,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, body, type, channel, language, is_default, created_at, updated_at, image_url, image_key
`

type UpdateTemplateParams struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Body      string      `json:"body"`
	Type      string      `json:"type"`
	Channel   string      `json:"channel"`
	ImageUrl  pgtype.Text `json:"image_url"`
	ImageKey  pgtype.Text `json:"image_key"`
	Language  pgtype.Text `json:"language"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Body,
		arg.Type,
		arg.Channel,
		arg.ImageUrl,
		arg.ImageKey,
		arg.Language,
		arg.IsDefault,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.Type,
		&i.Channel,
		&i.Language,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImageKey,
	)
	return i, err
}
